patroni:
  config:
    log:
      level: DEBUG
  scope: test
  superuserPassword: postgres
  replicationPassword: replication
  rewindPassword: rewind
  roleCreate: true

serviceAccount:
  create: true

env:
  PATRONI_KUBERNETES_NAMESPACE:
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  PATRONI_KUBERNETES_POD_IP:
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  PATRONI_KUBERNETES_USE_ENDPOINTS: "true"
  # PATRONI_KUBERNETES_BYPASS_API_SERVICE: "true"
  PATRONI_KUBERNETES_LABELS: |
    {{- $selectorLabels := include "common.helpers.labels.selectorLabels" . | fromYaml -}}
    {{- toJson $selectorLabels -}}
  PATRONI_KUBERNETES_CACERT: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  KUBERNETES_SERVICE_HOST: kubernetes.default.svc.cluster.local
