#==============================================================#
# 0420 pg_wait
#==============================================================#
pg_wait:
  name: pg_wait
  desc: PostgreSQL backend client count group by wait event type since 9.6
  query: |
    SELECT coalesce(datname, '_system') AS datname, coalesce(wait_event_type, 'Running') AS event, count(*) AS count FROM pg_stat_activity GROUP BY 1, 2;
  ttl: 10
  min_version: 090600
  tags: [ cluster ]
  metrics:
    - datname: { usage: LABEL ,description: Name of the database, _system for global process }
    - event:   { usage: LABEL ,description: Wait event type }
    - count:   { usage: GAUGE ,description: Count of WaitEvent on target database }


