#==============================================================#
# 0620 pg_db_confl
#==============================================================#
# https://pgpedia.info/p/pg_stat_database_conflicts.html

pg_db_confl_16:
  name: pg_db_confl
  desc: PostgreSQL database conflicts metrics for PG16+
  query: SELECT * FROM pg_stat_database_conflicts;
  ttl: 10
  min_version: 160000
  tags: [ cluster, replica ]
  metrics:
    - datid:                { usage: DISCARD }
    - datname:              { usage: LABEL  ,description: Name of this database }
    - confl_tablespace:     { usage: COUNTER ,description: Number of queries in this database that have been canceled due to dropped tablespaces }
    - confl_lock:           { usage: COUNTER ,description: Number of queries in this database that have been canceled due to lock timeouts }
    - confl_snapshot:       { usage: COUNTER ,description: Number of queries in this database that have been canceled due to old snapshots }
    - confl_bufferpin:      { usage: COUNTER ,description: Number of queries in this database that have been canceled due to pinned buffers }
    - confl_deadlock:       { usage: COUNTER ,description: Number of queries in this database that have been canceled due to deadlocks }
    - confl_active_logicalslot: { usage: COUNTER ,description: Number of uses of logical slots in this database that have been canceled due to old snapshots or too low a wal_level on the primary }

pg_db_confl_15:
  name: pg_db_confl
  desc: PostgreSQL database conflicts metrics for pg 9.1 - 16
  query: SELECT * FROM pg_stat_database_conflicts;
  ttl: 10
  min_version: 90100
  max_version: 160000
  tags: [ cluster, replica ]
  metrics:
    - datid:                { usage: DISCARD }
    - datname:              { usage: LABEL  ,description: Name of this database }
    - confl_tablespace:     { usage: COUNTER ,description: Number of queries in this database that have been canceled due to dropped tablespaces }
    - confl_lock:           { usage: COUNTER ,description: Number of queries in this database that have been canceled due to lock timeouts }
    - confl_snapshot:       { usage: COUNTER ,description: Number of queries in this database that have been canceled due to old snapshots }
    - confl_bufferpin:      { usage: COUNTER ,description: Number of queries in this database that have been canceled due to pinned buffers }
    - confl_deadlock:       { usage: COUNTER ,description: Number of queries in this database that have been canceled due to deadlocks }


