#==============================================================#
# 0730 pg_seq
#==============================================================#
pg_seq:
  desc: PostgreSQL sequence metrics
  query: SELECT CURRENT_CATALOG AS datname, schemaname || '.' || sequencename AS seqname, last_value, blks_read, blks_hit FROM pg_sequences s, LATERAL (SELECT relid, blks_read, blks_hit FROM pg_statio_all_sequences sio WHERE s.schemaname = sio.schemaname AND s.sequencename = sio.relname LIMIT 1) d LIMIT 128;
  ttl: 10
  min_version: 100000
  metrics:
    - datname:             { usage: LABEL    ,description: Database name of this sequence }
    - seqname:             { usage: LABEL    ,description: Fully schema qualified sequence name }
    - last_value:          { usage: COUNTER  ,description: The last sequence value written to disk }
    - blks_read:           { usage: COUNTER  ,description: Number of disk blocks read from this sequence }
    - blks_hit:            { usage: COUNTER  ,description: Number of buffer hits in this sequence }


