#==============================================================#
# 0820 pg_table_bloat
#==============================================================#
# pg_table_bloat require auxiliary view to work. Disable it or create auxiliary view before use:
pg_table_bloat:
  name: pg_table_bloat
  desc: PostgreSQL table bloat metrics, require auxiliary view pg_table_bloat to work
  query: SELECT datname, nspname || '.' || relname AS relname, size, ratio FROM pg_table_bloat ORDER BY size DESC LIMIT 64;
  ttl: 300
  timeout: 2
  min_version: 090400
  skip: true
  metrics:
    - datname:             { usage: LABEL    ,description: Database name of this table }
    - relname:             { usage: LABEL    ,description: Schema qualified name of this table }
    - size:                { usage: GAUGE    ,description: Total bytes of this table }
    - ratio:               { usage: GAUGE    ,description: Estimated bloat ratio of this table from 0 to 1 }


