#==============================================================#
# 0910 pgbouncer_list
#==============================================================#
# http://www.pgbouncer.org/usage.html#show-lists
pgbouncer_list:
  name: pgbouncer_list
  desc: Pgbouncer entry list
  query: SHOW LISTS;
  ttl: 10
  min_version: 10800
  fatal: true
  tags: [ pgbouncer ]
  metrics:
    - list:                { usage: LABEL                 ,description: Pgbouncer internal list name }
    - items:               { usage: GAUGE                 ,description: Number of corresponding pgbouncer object }


