configMaps:
  blocky-config:
    data:
      config.yml: |
        upstreams:
          init:
            # Configure startup behavior.
            # accepted: blocking, failOnError, fast
            # default: blocking
            strategy: fast
          groups:
            default:
              # Cloudflare
              - 1.1.1.1
              - 1.0.0.1
          strategy: parallel_best
          timeout: 2s
          # optional: HTTP User Agent when connecting to upstreams. Default: none
          userAgent: none

        # optional: Determines how blocky will create outgoing connections. This impacts both upstreams, and lists.
        # accepted: dual, v4, v6
        # default: dual
        connectIPVersion: dual

        # optional: ports configuration
        ports:
          # optional: DNS listener port(s) and bind ip address(es), default 53 (UDP and TCP). Example: 53, :53, "127.0.0.1:5353,[::1]:5353"
          dns: 53
          # optional: Port(s) and bind ip address(es) for DoT (DNS-over-TLS) listener. Example: 853, 127.0.0.1:853
          tls: 853
          # optional: Port(s) and optional bind ip address(es) to serve HTTPS used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:443. Example: 443, :443, 127.0.0.1:443,[::1]:443
          https: 443
          # optional: Port(s) and optional bind ip address(es) to serve HTTP used for prometheus metrics, pprof, REST API, DoH... If you wish to specify a specific IP, you can do so such as 192.168.0.1:4000. Example: 4000, :4000, 127.0.0.1:4000,[::1]:4000
          http: 4000

        # optional: logging configuration
        log:
          # optional: Log level (one from debug, info, warn, error). Default: info
          level: info
          # optional: Log format (text or json). Default: text
          format: text
          # optional: log timestamps. Default: true
          timestamp: true
          # optional: obfuscate log output (replace all alphanumeric characters with *) for user sensitive data like request domains or responses to increase privacy. Default: false
          privacy: false

persistence:
  config:
    mount:
    - path: /app/config.yml
      subPath: config.yml
    spec:
      useFromChart: true
      configMap:
        name: blocky-config
