{{- if and (.Values.wireguard).enabled (.Values.wireguard.config).secretData (not (.Values.wireguard.config).existingSecret) (not (.Values.wireguard.config).existingConfigMap) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.wireguardConfigName" . }}
  labels:
    {{- include "common.helpers.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $configFile, $content := (.Values.wireguard.config).secretData }}
    {{- $configFile | nindent 2 }}: {{ $content | b64enc }}   
  {{- end }}

---
{{- end }}
{{ include "common.secret" . }}