# Default values for bind9.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
workloadType: Deployment

# strategy:
#   type: RollingUpdate

image:
  repository: internetsystemsconsortium/bind9
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# hostname: bind9
# subdomain: localdomain
dnsPolicy: "ClusterFirst"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# env: {}

bind9:
  namedConfGenerator:
    enabled: false
    includes: /etc/bind/named.d/
  zoneCopy:
    enabled: false
    source: /etc/bind/zones/
    destination: /var/cache/bind/
    overwrite: false
  keyGenerator:
    path: /etc/bind/conf.d/
    enabled: false
    # keys: []
  forwarderGenerator:
    path: /etc/bind/conf.d/
    enabled: false
    # forwarders:
    #   google:
    #     dns:
    #     - dns.google.com
    #   cloudflare:
    #     ip:
    #     - 1.1.1.1
    #     - 1.0.0.1

args:
- -f
- -c
- /etc/bind/named.conf

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  main:
    type: ClusterIP
    ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: dns-tls
      port: 853
      protocol: TCP
    - name: rndc
      enabled: false
      port: 953
      protocol: TCP

probe:
  liveness:
    enabled: true
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 10
    tcpSocket:
      port: dns-udp

  readiness:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 10
    tcpSocket:
      port: dns-udp

  startup:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 10
    exec:
      command:
      - named-checkconf
      - /etc/bind/named.conf

persistence: {}
  # config:
  #   enabled: true
  #   mount:
  #   - path: /etc/bind
  #   spec:
  #     emptyDir: {}

ingress:
  main:
    enabled: false
    targetSelector:
      main: https
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
      # servicePort: 80
      # serviceName: otherService
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
