name: Release Charts

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0

    - name: Strip prerelease number from chart versions
      shell: bash
      run: .ci/strip-prerelease-version.sh

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: v3.14.4

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        charts_dir: charts
        config: cr.yaml
        skip_existing: true
        pages_branch: gh-pages
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  oci-push:
    name: Push release versions
    uses: ./.github/workflows/oci-build-and-push.yaml
    needs: release
    with:
      build_prerelease: false
    secrets: inherit